### ISSUE TITLE
Add and Remove node is not part of iostack

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-ha#169]
https://github.com/Seagate/cortx-ha/blob/604061cca190edc7803a7c57da73aa7b85861cae/conf/setup-ees.yaml#L55

Move add and remove node to setup.yaml which is part of ha config file not iostack

```
  remove_node:
    script: /opt/seagate/cortx/ha/conf/script/cluster_update
    args: remove_node
  add_node:
    script: /opt/seagate/cortx/ha/conf/script/cluster_update
    args: add_node
```
