### ISSUE TITLE
Improve installation path of setup-ees.yaml

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx-ha#84]
@mssawant, @ajay-paratmandali, [CC: @saurabhkhanvilkar ]
Rename and move the file `/opt/seagate/cortx/ha/conf/setup-ees.yaml` to `/opt/seagate/cortx/iostack-ha/conf/setup.yaml`.

Also rename the contents as:
```
iostack-ha:
  post_install:
    script: /opt/seagate/cortx/ha/conf/script/build-ees-ha
    args:
      - --init
      - /var/lib/hare/cluster.yaml
      - /opt/seagate/cortx/ha/conf/build-ees-ha-args.yaml
  init:
    script: /opt/seagate/cortx/ha/conf/script/build-ees-ha
    args:
      - /var/lib/hare/cluster.yaml
      - /opt/seagate/cortx/ha/conf/build-ees-ha-args.yaml
  config:
    script: null
    args: null
  test:
    script: null
    args: null
  reset:
    script: /opt/seagate/cortx/ha/conf/script/prov-ha-reset
    args: null
  backup:
    files:
      - /var/lib/hare/build-ees-ha*-args.yaml
      - /var/lib/hare/cluster.yaml
      - /var/lib/hare/confd.*
      - /var/lib/hare/consul-*
      - /var/lib/hare/node-name
      - /var/lib/hare/hax-env-*
      - /etc/corosync/corosync.conf
  post_update:
    script: /opt/seagate/cortx/ha/conf/script/build-ees-ha-update
    args:
      - /var/lib/hare/cluster.yaml
      - /opt/seagate/cortx/ha/conf/build-ees-ha-args.yaml
      - /opt/seagate/cortx/ha/conf/build-ees-ha-csm-args.yaml
  remove_node:
    script: /opt/seagate/cortx/ha/conf/script/cluster_update
    args: remove_node
  add_node:
    script: /opt/seagate/cortx/ha/conf/script/cluster_update
    args: add_node
```

**Justification**:
It becomes easy for provisioner to identify setup.yaml as a name and have a separate component for iteration logic in batch processing.
